CREATE USER 'dw_video'@'%' IDENTIFIED BY 'dw_video';

GRANT SELECT, INSERT, UPDATE, DELETE, CREATE, DROP, RELOAD, INDEX, ALTER, SHOW DATABASES, LOCK TABLES, CREATE VIEW, SHOW VIEW ON *.* TO 'dw_video'@'%';

