<?php
$GLOBALS += array(
	'docMap' => array(
        'vsub' => array('extra/vsub/readme.md', '多玩视频订阅文档'),
        'huyaPR' => array('extra/huya/playrecord.readme.md', '虎牙播放记录文档'),
	    'huyaMsg' => array('extra/huya/msg.readme.md', '虎牙消息接口文档'),
	    'huyaPlaysum' => array('extra/huya/playsum.readme.md', '虎牙播放量、订阅量接口文档(旧播客成长体系用)'),
	    'huyaUserHome' => array('extra/huya/userhome.readme.md', '虎牙个人主页相关接口(20150916)'),
	    'huyaRevenue' => array('extra/huya/revenue.readme.md', '虎牙分成体系(20151023)'),
		'duowanvideoCmsApi' => array('extra/duowanvideo/cms_api.md', '多玩视频 - 提供给发布器的API(20161220)'),
        'duowanvideoMipApi' => array('extra/duowanvideo/mip_api.md', '多玩视频 - 提供给百度MIP的内部API(20170413)'),
		'duowanvideoCommonFedApi' => array('extra/duowanvideo/common_fed_api.md', '多玩视频 - 通用前端API(20161220)'),
        'duowanvideoFanhePcApi' => array('extra/duowanvideo/fanhe_pc_api.md', '多玩视频 - 提供给饭盒视频助手的API(20170306)'),
        'duowanvideoFanheServerApi' => array('extra/duowanvideo/fanhe_server_api.md', '多玩视频 - 提供给饭盒后端的API (20170313)'),
        'duowanvideoAuthorgrabFedApi' => array('extra/duowanvideo/authorgrab_fed_api.md', '订阅号追踪 - 前端API (20170616)'),
        'duowanvideoAuthorgrabServerApi' => array('extra/duowanvideo/authorgrab_server_api.md', '订阅号追踪 - 后端API (20171021)'),
        'duowanvideoAuthorgrabPcApi' => array('extra/duowanvideo/authorgrab_pc_api.md', '订阅号追踪 - 提供给PC视频上传助手的单个视频抓取API (20170905)'),
        'relate4server' => array('extra/duowanvideo/relate4server.md', '服务器关联的外部服务'),
        'adsysDbDesign' => array('extra/adsys/ad_sys_db.md', '多玩广告系统数据库设计草稿(20170112)'),
        'adsysDbDesignSql' => array('extra/adsys/ad_sys_db.sql', '多玩广告系统数据库设计SQL(20170112)'),
        'yyliveAd' => array('extra/adsys/yylive_ad.md', 'YY联运广告后端特殊文档(20180306)'),
        'matchGuess' => array('extra/matchguess/match.md', '赛事竞猜接口(20180330)'),
        'adSyOutsource' => array('extra/adsys/ad_sy_outsource.md', '手游联运-广告位外包接口文档(20180416)'),
        'userAutoBet' => array('extra/eosget/user_auto_bet.md', '用户自动下注策略接口(20181031)'),
        'auction' => array('extra/eosget/auction.md', 'EOS竞拍活动接口(20181205)'),
    ),
);